name: Code Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUST_VERSION: 1.87.0

jobs:
  coverage:
    name: Generate Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_VERSION }}
          components: llvm-tools-preview

      - name: Setup Soroban target
        run: |
          # Try to add wasm32v1-none, fallback to wasm32-unknown-unknown
          rustup target add wasm32v1-none || rustup target add wasm32-unknown-unknown

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-coverage-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-coverage-

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Generate coverage
        run: |
          # Generate coverage data
          cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info
          
          # Also generate coverage report in text format for PR comments
          cargo llvm-cov --all-features --workspace --text --output-path coverage.txt
          
          # Generate HTML report
          cargo llvm-cov --all-features --workspace --html
          
          # Print coverage summary
          echo "Coverage Summary:"
          cat coverage.txt

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
          verbose: true

      - name: Upload coverage reports to artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report
          path: |
            lcov.info
            coverage.txt
            target/llvm-cov/html/
          retention-days: 1
