name: Build and Release

on:
  push:
    tags:
      - 'v*'  # triggered whenever a new tag (prefixed with "v") is pushed to the repository

jobs:
  release-contango-contract:
    uses: stellar-expert/soroban-build-workflow/.github/workflows/release.yml@main
    with:
      release_name: ${{ github.ref_name }}          # use git tag as unique release name
      release_description: 'Contango Token Contract Release'
      package: 'contango-token-contract'            # package name from Cargo.toml
      make_target: 'build'                          # make target to invoke (defined in Makefile)
    secrets:
      release_token: ${{ secrets.GITHUB_TOKEN }}    # authentication token automatically created by GitHub
